version: '3.8'

services:
  app:
    container_name: spring-boot-app
    image: ${DOCKER_IMAGE}
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PWD}
      SERVER_PORT: ${PORT}
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PWD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf

  react-app:
    image: ${REACT_IMAGE}
    container_name: react-app
    ports:
      - "80:80"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - react-app
      - app

volumes:
  mysql-data:
