name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # Gradle 권한부여
      - name: Grant execute permission for Gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      
      # 2. Gradle Build
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build -x test

      # 3. Docker Hub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Docker 이미지 빌드
      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      # 5. Docker 이미지 Push
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE }}
        
      # React 이미지 빌드 & Push
      - name: Build React Docker image
        working-directory: ./frontend
        run: docker build -t ${{ secrets.REACT_IMAGE }} .

      - name: Push React Docker image
        run: docker push ${{ secrets.REACT_IMAGE }}

        
      # 6. SSH to EC2 + Pull & Compose
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_IMAGE }}
            cd /home/ubuntu/docker-compose
            docker-compose up -d --no-deps app
