name: CI/CD Spring Boot Docker to EC2 (Secrets-based)

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 설치 (Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. Docker Hub 로그인 (Private 이미지일 경우)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      # 6. Docker 이미지 Push (선택)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE }}

      # 7. EC2에 SSH 접속 후 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app
            git pull origin main
            export DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USER_NAME=${{ secrets.DB_USER_NAME }}
            export DB_USER_PWD=${{ secrets.DB_USER_PWD }}
            export DB_ROOT_PWD=${{ secrets.DB_ROOT_PWD }}
            docker-compose down
            docker-compose up -d --build
